scene:
  ANIMATED_CHARACTERS:
    - character_cfg: examples/characters/char7/char_cfg.yaml
      motion_cfg: examples/config/motion/greeBounce.yaml
      retarget_cfg: examples/config/retarget/mixamo_fff.yaml

controller:
  MODE: video_render
  OUTPUT_VIDEO_PATH: temp/bounce.gif