#char_cfg: 그리 정보가 담긴 yaml
# motion_cfg: 사용할 애니메이션 yaml
# retarget_cfg: 우리가 만든 애니메이션 쓸거면 건들거 없음, 주어진 기본 애니메이션 쓸거면 수정 필요 

scene:
  ANIMATED_CHARACTERS:
    - character_cfg: examples/characters/charSample/char_cfg.yaml 
      motion_cfg: examples/config/motion/greeWave.yaml 
      retarget_cfg: examples/config/retarget/rokokoTest_mixamo.yaml

controller:
  MODE: video_render
  OUTPUT_VIDEO_PATH: ./video.gif